import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { theme } from "@/styles/theme"
import 'antd/dist/reset.css';
import { I18nProviderClient } from "../../../locales/client";
import { ReactElement } from "react";
import { StoreProvider } from "../storeProvider";
import Locale from 'intl-locale-textinfo-polyfill'


export const metadata: Metadata = {
  title: "Create Next & Redux App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: { children: ReactElement, params: Promise<{ locale: string }> }) {
  const { locale } = await params
  const { direction: dir } = new Locale(locale).textInfo
  return (
    <html lang={locale} dir={dir}>
      <body suppressHydrationWarning={true}>
        <StoreProvider>
          <I18nProviderClient locale={locale}>
            <AntdRegistry>
              <ConfigProvider theme={theme} >
                {children}
              </ConfigProvider>
            </AntdRegistry>
          </I18nProviderClient>
        </StoreProvider>
      </body>
    </html>
  );
}
